### ISSUE TITLE
Checklist for Task no.3

### ISSUE THREAD

**Issue by MasterKiller1239** [MasterKiller1239/Tpum_project#4]
- [x] the program is in .NET
- [x] the program compiles
- [x] unit tests in green
- [x] two program instances can be created simultaneously (two processes)
- [ ] server and client instances work together (integration test)
- [ ] Both programs have the required Presentation, Logic, and Data layers
- [ ] The programs communicate using the WebSocket
- [ ] Both programs use a common object model
- [ ] Interactive interaction was used
- [ ] Reactive cooperation (spontaneous / subscription) was used with the use of the subscription mechanism realized by implementing IObservable
- [ ] Serialization using one of the syntax `JSON`,` YAML`, `XML`
- [ ] the critical section was separated and the consistency of the data was ensured
- [ ] A data exchange model with the use of OPC UA was developed
- [ ] Harmonization of models - an equivalent model was generated and compared to the handwritten one
